import type { AramaForm } from "../../add/Components/steps";

export const updateData: { sampleAramaData: Partial<AramaForm> } = {
  sampleAramaData: {
    arama_name: "Sample Sil Mathā Aramaya",
    arama_address: "123 Temple Street, Colombo 07",
    telephone_number: "011-2345678",
    whatsapp_number: "0712345678",
    email_address: "arama@example.com",
    province: "CP",
    district: "DC006",
    divisional_secretariat: "DS0076",
    provincial_sasanaarakshaka_council: "Western Province Council",
    grama_niladhari_division: "2-3-09-310",
    chief_nun_name: "Ven. Sil Mathā Name",
    chief_nun_registration_number: "REG123456",
    established_period: "2020",
    land_size: "2 acres",
    land_ownership: "Private",
    legal_ownership_proof: "Grant Deed, Tax Receipt",
    existing_buildings_facilities: "Main temple building, meditation hall, residential quarters",
    donor_families_count: "50",
    committees: "Donor Society, Working Committee",
    arama_owned_land: JSON.stringify([{
      id: "land-1",
      serialNumber: 1,
      landName: "Main Land",
      village: "Colombo",
      district: "Colombo",
      extent: "2 acres",
      cultivationDescription: "Temple buildings",
      ownershipNature: "Bandara",
      deedNumber: "DEED001",
      titleRegistrationNumber: "TITLE001",
      taxDetails: "Paid",
      landOccupants: "Temple"
    }]),
    land_info_certified: true,
    resident_silmathas: JSON.stringify([{
      id: "silmatha-1",
      serialNumber: 1,
      silmathaName: "Ven. Sil Mathā One",
      registrationNumber: "REG001",
      occupationEducation: "Studying"
    }]),
    resident_silmathas_certified: true,
    inspection_report: "The arama is well maintained with proper facilities for resident sil mathā.",
    inspection_code: "INSP001",
    ownership_district: "Colombo",
    ownership_divisional_secretariat: "Colombo Divisional Secretariat",
    ownership_grama_niladhari_division: "GN001",
    ownership_arama_name: "Sample Sil Mathā Aramaya",
    pooja_deed_obtained: true,
    government_pooja_deed_obtained: false,
    government_pooja_deed_in_progress: true,
    institution_name: "Buddhist Affairs Department",
    institution_consent_obtained: true,
    recommend_new_center: true,
    recommend_registered_arama: false,
    annex2_chief_nun_registered: true,
    annex2_land_ownership_docs: true,
    annex2_institution_consent: true,
    annex2_district_association_recommendation: true,
    annex2_divisional_secretary_recommendation: true,
    annex2_recommend_district: "Colombo",
    annex2_recommend_divisional_secretariat: "Colombo Divisional Secretariat",
    annex2_recommend_grama_niladhari_division: "GN001",
    annex2_recommend_arama_name: "Sample Sil Mathā Aramaya",
    secretary_approve_construction: true,
    secretary_not_approve_construction: false,
    secretary_refer_registration: false,
    secretary_refer_resubmission: false,
    secretary_resubmission_notes: ""
  }
};

