type Environment = "LOCAL" | "DEVELOP" | "PRODUCTION";

const environment = "DEVELOP" as Environment;

export const baseURL: string | undefined =
  environment === "LOCAL"
    ? process.env.NEXT_PUBLIC_BASE_URL_LOCAL
    : environment === "DEVELOP"
    ? process.env.NEXT_PUBLIC_BASE_URL_DEV
    : process.env.NEXT_PUBLIC_BASE_URL;

// DEPARTMENT
export const BHIKKU_MANAGEMENT_DEPARTMENT = "Bhikku Management";
export const SILMATHA_MANAGEMENT_DEPARTMENT = "Silmatha Management";
export const SYSTEM_ADMIN_MANAGEMENT_DEPARTMENT = "System Administration";
export const DAMMA_SCHOOL_MANAGEMENT_DEPARTMENT = "Damma School";
export const DIVITIONAL_SEC_MANAGEMENT_DEPARTMENT = "Divisional Secretariat";
export const PUBLIC_MANAGEMENT_DEPARTMENT = "Public Services";
export const VIHARA_MANAGEMENT_DEPARTMENT = "Vihara Department";

export const COMMON_VISIBLE_DEPARTMENTS = [
  BHIKKU_MANAGEMENT_DEPARTMENT,
  SILMATHA_MANAGEMENT_DEPARTMENT,
  SYSTEM_ADMIN_MANAGEMENT_DEPARTMENT,
  DAMMA_SCHOOL_MANAGEMENT_DEPARTMENT,
  DIVITIONAL_SEC_MANAGEMENT_DEPARTMENT,
  PUBLIC_MANAGEMENT_DEPARTMENT,
  VIHARA_MANAGEMENT_DEPARTMENT,
];

export const COMMON_VISIBLE_DEPARTMENTS_EXCLUDING_DIVISIONAL_SEC =
  COMMON_VISIBLE_DEPARTMENTS.filter(
    (department) => department !== DIVITIONAL_SEC_MANAGEMENT_DEPARTMENT
  );

export const SIDEBAR_ACCESS_MAP: Record<string, string[]> = {
  "/": COMMON_VISIBLE_DEPARTMENTS,
  "/print-request": COMMON_VISIBLE_DEPARTMENTS,
  "/qr-scan": COMMON_VISIBLE_DEPARTMENTS,
  "/objections": COMMON_VISIBLE_DEPARTMENTS_EXCLUDING_DIVISIONAL_SEC,
  "/bhikkhu": [BHIKKU_MANAGEMENT_DEPARTMENT, SYSTEM_ADMIN_MANAGEMENT_DEPARTMENT],
  "/silmatha": [SILMATHA_MANAGEMENT_DEPARTMENT, SYSTEM_ADMIN_MANAGEMENT_DEPARTMENT],
  "/temple/arama": [SILMATHA_MANAGEMENT_DEPARTMENT, SYSTEM_ADMIN_MANAGEMENT_DEPARTMENT],
  "/temple/vihara": [VIHARA_MANAGEMENT_DEPARTMENT, SYSTEM_ADMIN_MANAGEMENT_DEPARTMENT],
  "/temple/dewala": [VIHARA_MANAGEMENT_DEPARTMENT, SYSTEM_ADMIN_MANAGEMENT_DEPARTMENT],
  "/teachers": [VIHARA_MANAGEMENT_DEPARTMENT, SYSTEM_ADMIN_MANAGEMENT_DEPARTMENT],
  "/admin": [VIHARA_MANAGEMENT_DEPARTMENT, SYSTEM_ADMIN_MANAGEMENT_DEPARTMENT, SILMATHA_MANAGEMENT_DEPARTMENT],
};


//ROLE_LEVEL
export const ADMIN_ROLE_LEVEL = 'ADMIN';
export const DATAENTRY_ROLE_LEVEL = 'DATA_ENTRY';
