import type { ViharaForm } from "../../add/Components/steps";

export const updateData: { sampleViharaData: Partial<ViharaForm> } = {
  sampleViharaData: {
    temple_name: "Sample Buddhist Temple",
    temple_address: "123 Temple Street, Colombo 07",
    telephone_number: "011-2345678",
    whatsapp_number: "0712345678",
    email_address: "temple@example.com",
    province: "CP",
    district: "DC006",
    divisional_secretariat: "DS0076",
    pradeshya_sabha: "Central Province Council",
    grama_niladhari_division: "2-3-09-310",
    nikaya: "NK001",
    parshawaya: "PR002",
    viharadhipathi_name: "Ven. Chief Incumbent Name",
    period_established: "2020",
    buildings_description: "Main temple building, meditation hall, residential quarters",
    dayaka_families_count: "100",
    kulangana_committee: "Active committee with 10 members",
    dayaka_sabha: "Regular meetings held monthly",
    temple_working_committee: "5 member committee",
    other_associations: "Buddhist Youth Association",
    temple_lands: JSON.stringify([{
      id: "land-1",
      serialNumber: 1,
      landName: "Main Land",
      village: "Colombo",
      district: "Colombo",
      extent: "2 acres",
      cultivationDescription: "Temple buildings",
      ownershipNature: "Bandara",
      deedNumber: "DEED001",
      titleRegistrationNumber: "TITLE001",
      taxDetails: "Paid",
      landOccupants: "Temple"
    }]),
    land_info_certified: true,
    resident_bhikkhus: JSON.stringify([{
      id: "bhikkhu-1",
      serialNumber: 1,
      bhikkhuName: "Ven. Bhikkhu One",
      registrationNumber: "REG001",
      occupationEducation: "Studying"
    }]),
    resident_bhikkhus_certified: true,
    inspection_report: "The temple is well maintained with proper facilities for resident bhikkhus.",
    inspection_code: "INSP001",
    grama_niladhari_division_ownership: "GN001",
    sanghika_donation_deed: true,
    government_donation_deed: false,
    government_donation_deed_in_progress: true,
    authority_consent_attached: true,
    recommend_new_center: true,
    recommend_registered_temple: false,
    annex2_recommend_construction: true,
    annex2_land_ownership_docs: true,
    annex2_chief_incumbent_letter: true,
    annex2_coordinator_recommendation: true,
    annex2_divisional_secretary_recommendation: true,
    annex2_approval_construction: true,
    annex2_referral_resubmission: false,
  }
};

